version: '3.3'

services:
  node-exporter:
    privileged: true
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.ignored-mount-points"
      - "^/(rootfs/)?(dev|etc|host|proc|run|sys|volume1)($$|/)"
      - '--collector.bonding'
      
  prometheus:
  
    image: prom/prometheus
    container_name: prometheus
    restart: always
    links:
      - node-exporter
    ports:
      - "9090:9090"
    volumes:
      - ${PROMETHEUS_ROOT}/configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ${PROMETHEUS_ROOT}/data/prometheus:/prometheus
